### ISSUE TITLE
Add config file for CLI to ease multicluster interaction

### ISSUE THREAD

**Issue by emmanuel** [Nordstrom/kubelogin#10]
First, a few assumptions and assertions:

* `kubelogin` will be used with multiple target clusters
* `kubelogin` should not assume the structure of the URL that the `kubelogin` server is deployed at (i.e., by accepting a cluster ID and appending, prepending or interpolating that into a full URL). So the CLI should accept the full URL of the `kubelogin` server deployment. 
* it is unreasonable to expect `kubelogin` users to type the full URL of the target `kubelogin` server in every invocation

Therefore we should provide a mechanism for configuring `kubelogin` to associate a friendly name with a specific `kubelogin` server URL, so that users can simply type `kubelogin $FRIENDLY_NAME` and `kubelogin` will initiate the login sequence. 

Basically, I see the work as:

* introduce a package for YAML handling (parsing and emitting)
* write a hidden file into the user's home directory (e.g., `~/.kubeloginrc`). There should be a top-level map, whose only key (today) will be `servers`, the value that the `servers` key points to will be a map, and within *that* map, each key will be the **alias** of a specific `kubelogin` server deployment.[1]
* add an argument for configuring new target `kubelogin` servers.[2] This will parse the existing YAML config file (if one exists, or create a file if not) and then either insert a new key for the specified alias, or replace the existing URL for the specified alias

[1] example `~/.kubeloginrc`:
```
servers:
  foo:
    base-url: https://kubelogin.foo.example.com
  bar:
    base-url: https://kubelogin.bar.example.com
```
[2] ex: `kubelogin -s foo -u https://kubelogin.foo.example.com`

**Comment by emmanuel** [comment]
Forgot that we're going to need the user to specify which `kubectl` user to store the JWT token into. So let's structure the CLI as `kubelogin $VERB`, where there are two verbs: `config` (for creating/updating config) and `login` (for actually performing a login).

Ex:
```
kubelogin config --alias=prod --server=https://cluster_name.example.com --kubectl-user=foo_user_prod
kubelogin login prod
```

In order to allow users to login without setting up a config beforehand, the `login` verb should also accept command-line flag that specify the `kubelogin` server URL and `kubectl` user (which would otherwise be provided to `kubelogin config ...`). Ex: `kubelogin login --server=https://cluster_name.example.com --kubectl-user=foo_user_prod`.

**Comment by emmanuel** [comment]
If it's ugly to branch between `kubelogin login $ALIAS` and `kubelogin login --server=https://foo.example.com --kubectl-user=foo_user_prod` then go ahead and make the alias an arg:

```
kubelogin login --alias=prod
```

**Comment by emmanuel** [comment]
Per discussion, please target this as a format:

```
servers:
- alias: prod
  base-url: https://kubelogin.foo.example.com
  kubectl-user: foo_user_prod
- alias: nonprod
  base-url: https://kubelogin.bar.example.com
  kubectl-user: foo_user_nonprod
```
